version: '3.8'

services:
  byeboros-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: byeboros-backend-app-2
    ports:
      - "8081:8080"
    env_file:
      - .env
    volumes:
      - ./service_account.json:/app/service_account.json:ro
    restart: unless-stopped
